"""
Klarity — The AI Layer for Mental Health Practices.
A patient-owned continuity layer. Not the therapist. The continuity.
"""

import streamlit as st

from mock_data import (
    MOCK_AGENT_OUTPUTS,
    PATIENT_247,
    PATIENT_PREP_NOTE,
    SESSIONS_1_TO_4,
    WEEK_MOOD_CHECKINS,
)

st.set_page_config(page_title="Klarity", page_icon="🌱", layout="centered")

# -------------------- CSS --------------------
st.markdown(
    """
    <style>
      .stApp { background-color: #FAF7F2; }
      h1, h2, h3, h4 { font-family: 'Lora', Georgia, serif; color: #2A2A2A; }
      .anchor-quote {
          font-family: 'Lora', Georgia, serif;
          font-size: 30px;
          line-height: 1.35;
          color: #2A2A2A;
          text-align: center;
          padding: 32px 16px 16px 16px;
      }
      .anchor-attrib {
          text-align: center;
          color: #6B7B6F;
          font-size: 13px;
          padding-bottom: 24px;
      }
      .brief-card {
          background-color: #FFFFFF;
          border-left: 4px solid #6B8E7F;
          border-radius: 12px;
          padding: 24px;
          box-shadow: 0 1px 4px rgba(0,0,0,0.04);
          margin-bottom: 16px;
      }
      .pattern-card {
          background-color: #FFF8F4;
          border-left: 4px solid #C97B5C;
          border-radius: 12px;
          padding: 20px;
          margin-bottom: 16px;
      }
      .takeaway-card {
          background-color: #FFFFFF;
          border-radius: 12px;
          padding: 24px;
          box-shadow: 0 1px 4px rgba(0,0,0,0.04);
          margin-bottom: 12px;
          border: 1px solid #EFEAE0;
      }
      .anchor-card {
          background-color: #FFFFFF;
          border-radius: 20px;
          padding: 16px;
          box-shadow: 0 4px 16px rgba(107,142,127,0.10);
          margin: 16px 0;
          border: 1px solid #EAE3D2;
      }
      .small-muted { color: #8A8A8A; font-size: 13px; }
      .pill-on  { color: #6B8E7F; font-weight: 600; }
      .pill-off { color: #B8B8B8; }
    </style>
    """,
    unsafe_allow_html=True,
)

# -------------------- Session state --------------------
DEMO_FLAGS = [
    "session_4_ended",
    "takeaway_approved",
    "anchor_delivered",
    "pattern_alert_fired",
    "brief_generated",
]
for k in DEMO_FLAGS:
    if k not in st.session_state:
        st.session_state[k] = False

# -------------------- Sidebar --------------------
view = st.sidebar.radio("View", ["Therapist", "Patient", "Demo Control"])

st.sidebar.markdown("---")
st.sidebar.caption("Demo state")
for k in DEMO_FLAGS:
    mark = "✓" if st.session_state[k] else "–"
    klass = "pill-on" if st.session_state[k] else "pill-off"
    label = k.replace("_", " ")
    st.sidebar.markdown(
        f"<span class='{klass}'>{mark}  {label}</span>",
        unsafe_allow_html=True,
    )


# -------------------- THERAPIST VIEW --------------------
def therapist_view():
    st.markdown("### Good morning, Dr. Chen")
    st.caption("Monday, May 11 · 3 sessions today")
    st.markdown("")

    # Section A — Pre-session brief
    if st.session_state["brief_generated"]:
        brief = MOCK_AGENT_OUTPUTS["brief"]["brief"]
        st.markdown(
            f"""
            <div class="brief-card">
              <strong>Patient #247 · Session 5 · Tuesday 2:00pm</strong><br><br>
              {brief}
            </div>
            """,
            unsafe_allow_html=True,
        )
        st.caption("Generated by Brief Agent · you reviewed at 8:42am")
    else:
        st.markdown(
            """
            <div class="brief-card">
              <span class="small-muted">
                Brief for Patient #247 will appear here once Session 5 prep is generated.
              </span>
            </div>
            """,
            unsafe_allow_html=True,
        )

    st.markdown("")

    # Section B — Pattern Agent alert
    if st.session_state["pattern_alert_fired"]:
        pattern = MOCK_AGENT_OUTPUTS["pattern"]
        with st.expander(
            "  Circling pattern detected — work boundaries × 4 weeks",
            expanded=True,
        ):
            st.markdown(
                f"""
                <div class="pattern-card">
                  <strong>{pattern['topic']}</strong><br><br>
                  {pattern['recommendation']}
                </div>
                """,
                unsafe_allow_html=True,
            )
            st.markdown("**Suggested resources**")
            for r in pattern["resources"]:
                st.markdown(f"• **{r['title']}** — *{r['why']}*")
            st.markdown("")
            c1, c2, c3 = st.columns(3)
            with c1:
                st.button("Suggest a values exercise", key="pat_b1")
            with c2:
                st.button("Surface their own Session 2 quote", key="pat_b2")
            with c3:
                st.button("Dismiss", key="pat_b3")
            st.caption(
                "You decide. Klarity never messages your patient without your approval."
            )

    # Section C — Session 4 takeaway candidates
    if st.session_state["session_4_ended"] and not st.session_state["takeaway_approved"]:
        st.markdown("#### From Session 4 · Scribe Agent")
        st.caption(
            "In Patient #247's own words. Pick one to send as their anchor this week."
        )
        for i, t in enumerate(MOCK_AGENT_OUTPUTS["scribe"]["candidate_takeaways"]):
            st.markdown(
                f"""
                <div class="takeaway-card">
                  <div style="font-family:'Lora',Georgia,serif;font-size:20px;line-height:1.4;">
                    "{t['phrase']}."
                  </div>
                  <div class="small-muted" style="margin-top:8px;">
                    From: <em>"{t['source_quote']}"</em>
                  </div>
                </div>
                """,
                unsafe_allow_html=True,
            )
            cols = st.columns([1, 1, 4])
            with cols[0]:
                if st.button("Approve & send", key=f"approve_{i}"):
                    st.session_state["takeaway_approved"] = True
                    st.rerun()
            with cols[1]:
                st.button("Edit", key=f"edit_{i}")
        st.markdown("")

    elif st.session_state["takeaway_approved"]:
        st.success(
            "Anchor sent. Patient #247 will see *“I'm allowed to celebrate my wins”* Tuesday 7am."
        )

    # Section D — Drop-off risk
    st.markdown("#### Engagement")
    c1, c2, c3 = st.columns(3)
    with c1:
        st.metric("Sessions attended", "4 of 5", delta="−1 no-show")
    with c2:
        st.metric("Drop-off risk", "Moderate", delta="↓ from High")
    with c3:
        st.metric("Last engagement", "2 days ago", delta="anchor tapped")
    st.caption(
        "Risk model uses attendance + engagement + circling signals. Explainable on click."
    )


# -------------------- PATIENT VIEW --------------------
def patient_view():
    cols = st.columns([1, 4, 1])
    with cols[1]:
        st.markdown("##### Tuesday morning")
        st.markdown("# Hi, friend 🌱")
        st.markdown("")

        # Section A — Daily anchor card
        if st.session_state["anchor_delivered"]:
            st.markdown(
                """
                <div class="anchor-card">
                  <div class="anchor-quote">
                    "I'm allowed to<br>celebrate my wins."
                  </div>
                  <div class="anchor-attrib">— You, Session 4</div>
                </div>
                """,
                unsafe_allow_html=True,
            )
            b1, b2, b3 = st.columns(3)
            with b1:
                st.button("This resonates today", key="res")
            with b2:
                st.button("Not today", key="not")
            with b3:
                st.button("Save to my Story", key="save")
        else:
            st.markdown(
                """
                <div class="anchor-card">
                  <div class="anchor-quote small-muted">
                    Your next anchor arrives after your<br>therapist reviews Session 4.
                  </div>
                </div>
                """,
                unsafe_allow_html=True,
            )

        st.markdown("")

        # Section B — Mood check-in
        st.markdown("**How's today landing?**")
        m = st.feedback("stars")
        if m is not None:
            st.toast("Logged. Thanks for checking in.")

        st.markdown("")

        # Section C — Prepping for Tuesday
        with st.expander("Prepping for Tuesday with Dr. Chen?", expanded=False):
            st.markdown("*Last 4 sessions you've talked about:*")
            st.markdown("- Work boundaries (4×)")
            st.markdown("- Perfectionism (3×)")
            st.markdown("- Celebrating wins (2×)")
            st.markdown("- Your sister's wedding (1×)")
            st.text_area(
                "Anything new you want to bring in?",
                placeholder="A sentence is enough.",
                key="prep_note",
            )
            st.button("Share with Dr. Chen before Tuesday", key="share_prep")

        # Section D — Your Story
        with st.expander("Your Story · portable, yours", expanded=False):
            st.caption(
                "This is the version of you Klarity carries between therapists. "
                "You own it. You can edit, hide, or take it with you anytime."
            )
            st.markdown("- *Started therapy because work was eating Saturdays.*")
            st.markdown(
                "- *Anchor that's landed: \"I'm allowed to celebrate my wins.\"*"
            )
            st.markdown("- *Working on: saying no without an essay.*")
            cc = st.columns(3)
            with cc[0]:
                st.button("Edit", key="story_edit")
            with cc[1]:
                st.button("Export", key="story_export")
            with cc[2]:
                st.button("Share with a new therapist", key="story_share")


# -------------------- DEMO CONTROL --------------------
def demo_control():
    st.title("Demo Control")
    st.caption("Click these in order during the live walkthrough.")
    st.markdown("---")

    steps = [
        (
            "▶ End Session 4 (trigger Scribe)",
            "session_4_ended",
            "3 takeaway candidates surfaced in Therapist View.",
            None,
        ),
        (
            "▶ Therapist approves anchor",
            "takeaway_approved",
            "Anchor queued for Tuesday 7am delivery.",
            "session_4_ended",
        ),
        (
            "▶ Tuesday morning (deliver anchor)",
            "anchor_delivered",
            "Anchor card live in Patient View.",
            "takeaway_approved",
        ),
        (
            "▶ Friday — fire Pattern Alert",
            "pattern_alert_fired",
            "Circling alert visible to Dr. Chen.",
            None,
        ),
        (
            "▶ Monday — generate Session 5 Brief",
            "brief_generated",
            "Pre-session brief live at top of Therapist View.",
            "anchor_delivered",
        ),
    ]

    for label, flag, status_msg, dep in steps:
        with st.container(border=True):
            cols = st.columns([3, 4])
            with cols[0]:
                disabled = (dep is not None and not st.session_state[dep]) or st.session_state[flag]
                if st.button(label, disabled=disabled, key=f"btn_{flag}"):
                    st.session_state[flag] = True
                    st.rerun()
            with cols[1]:
                if st.session_state[flag]:
                    st.success(status_msg)
                else:
                    st.caption(status_msg)

    st.markdown("---")
    cc = st.columns(2)
    with cc[0]:
        if st.button("Reset demo", type="secondary"):
            for k in DEMO_FLAGS:
                st.session_state[k] = False
            st.rerun()
    with cc[1]:
        st.caption(
            "Tip: keep Therapist tab open in one window, Patient in another. "
            "Drive everything from this tab."
        )

    st.markdown("##### Live state")
    state_rows = [{"flag": k, "active": st.session_state[k]} for k in DEMO_FLAGS]
    st.dataframe(state_rows, use_container_width=True, hide_index=True)


# -------------------- ROUTER --------------------
if view == "Therapist":
    therapist_view()
elif view == "Patient":
    patient_view()
else:
    demo_control()
